### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by badarshahzad** [goxr3plus/JavaFX-Web-Browser#1]
Why don't we should start from this https://github.com/badarshahzad/Jfx-Browser repository lets have fun on this repo  and start building an awesome Javafx Browser?
"Yes" "No" "Need time for thinking"

**Comment by goxr3plus** [comment]
Hello my friend I can help you with you Browser, you are welcome to take any features I have implemented here. My goal for the moment is different.

I made this Browser for XR3PLAYER, so my main intention is upgrading other programs :).

**Comment by goxr3plus** [comment]
@badarshahzad Also I want to let you know that I have downloaded you repository and working on improving it, reading how you have done things and I AM VERY VERY I IMPRESSED, especially with the download files feature.

Thank you for starring this repository.

**Comment by badarshahzad** [comment]
@goxr3plus  The download feature was implemented by [Naeem](https://github.com/naeemkhan12) he is an awesome guy and did a very impressive job. Although, we have minor flaws in history as during merging the code of all colleges we take abruptly decisions and this take us to bugs side. The bugs in just history maintaining.
I'll be happy if you test the code and you made some improvements init. I will wait for your pull request :+1:  hope you at least add remove or refine the code. 
:wave:

**Comment by goxr3plus** [comment]
Alright, I will be glad if you have more comments on your code in future applications. You can understand it only if you are Java Ninja :).

**Comment by badarshahzad** [comment]
Sorry man, we realize our blunders as we were in learning phase and this mistake was unacceptable but I hope you will get easily idea from methods name and classes. We made things easy with name convention to get an idea about structure of code. :smile:

**Comment by goxr3plus** [comment]
1)We should start by converting this to a Maven or Gradle project. I can do that easily to Maven Project.

2)So SEGP will be renamed to src and the folder testing should go under Maven testing resource folder.

I will have a look at it.

**Comment by badarshahzad** [comment]
:+1:  that's awesome idea

**Comment by badarshahzad** [comment]
:+1:  that's an awesome idea

**Comment by goxr3plus** [comment]
@badarshahzad  I committed a big pull request for your project ( https://github.com/badarshahzad/Jfx-Browser/pull/58 ) , when you accept it we can continue on making it beautiful . It's on your hand :)

**Comment by goxr3plus** [comment]
@badarshahzad Download the ready to run application to see on your own if i missed something  -> 
[JFX-Browser-1.0.0.zip](https://github.com/badarshahzad/Jfx-Browser/files/1455711/JFX-Browser-1.0.0.zip)
