### ISSUE TITLE
Exception in Application start method

### ISSUE THREAD

**Issue by kartikkumar783** [goxr3plus/JavaFX-Web-Browser#10]
Not Running ???

**Comment by goxr3plus** [comment]
If you fork master you need java 10 :)

**Comment by kartikkumar783** [comment]
Still Getting the same error :(

**Comment by goxr3plus** [comment]
@kartikkumar783  Ouh it's been time , maybe it's a little bit broken . Send me the `StackTrace` .

**Comment by goxr3plus** [comment]
Also what Operating System are you using and which Java Version and which IDE (Development Tool)

**Comment by kartikkumar783** [comment]
Please take a look at screenshot & I m using Windows 7 with Eclipse IDE and
JavaVersion 8

**Comment by goxr3plus** [comment]
Can't see any screenshot where it is :)?

**Comment by goxr3plus** [comment]
@kartikkumar783  No more details provided i can't proceed with this issue , closing.
